<%@ Page language="c#" Src="UploadHttpModuleFiles.aspx.cs" AutoEventWireup="false" Inherits="Brettle.Web.NeatUpload.UploadHttpModuleFiles" %>
<%@ Register TagPrefix="Upload" Namespace="Brettle.Web.NeatUpload" Assembly="Brettle.Web.NeatUpload" %>

<Html>
	<Head runat="server">
		<Title>Test of UploadHttpModule.Files Property</Title>
		<style type="text/css">
<!--
		.ProgressBar {
			margin: 0px;
			border: 0px;
			padding: 0px;
			width: 100%;
			height: 2em;
		}
-->
		</style>
	</Head>
	<Body>
		<form id="uploadForm" runat="server">
			<Upload:HiddenPostBackID runat="server" />
			<h1>NeatUpload Demo</h1>
			<p>
			This page tests the UploadHttpModule.Files property.  It should return an UploadedFileCollection of 
			UploadedFile objects, which corresponds to all the files that were uploaded, not just the ones that 
			correspond to NeatUpload's InputFile control.  Using UploadHttpModule.Files, the developer can 
			access files uploaded via standard &lt;input type="file"&gt; elements, even if those elements
			are dynamically generated by via client-side JavaScript.
			</p>
			<p>
			Now select some files and click Submit.
			</p>
			<p>
			Pick a file using a standard &lt;input type="file"&gt; element:
				<input type="file" name="inputFile"/><br />
			Pick a file using using NeatUpload's InputFile control:
				<Upload:InputFile id="inputFile2" runat="server" /><br />

			<asp:Button id="submitButton" runat="server" Text="Submit" />
			<asp:Button id="cancelButton" runat="server" Text="Cancel" CausesValidation="False"/><br />
			
			<pre id="bodyPre" runat="server">
			
			</pre>
			</p>
			<p>
			<Upload:ProgressBar id="inlineProgressBar" runat="server" inline="true" Triggers="submitButton" />
			The inline progress bar is an IFRAME.  If your browser doesn't support IFRAMEs, you'll see a link to
			display the progress bar in a new window.  The text of that link is configurable.
			</p>
		</form>
	</Body>
</Html>
