#!/bin/sh
rm "$1"/bin/SWFUpload.dll*
rm "$1"/bin/js.dll*
mkdir "$1"/NeatUpload

# Display the commands as they are executed
set -x
# Return an error if any of these fail
set -e
cp "$1"/../../js/install/*.js "$1"/NeatUpload/
cp "$1"/../../flash/src/SWFUpload/install/* "$1"/NeatUpload/
cp "$1"/../src/Brettle.Web.NeatUpload/install/NeatUpload/* "$1"/NeatUpload/
