//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploaderTest {
    
    public partial class DBWrite {
        protected System.Web.UI.HtmlControls.HtmlForm uploadForm;
        protected System.Web.UI.WebControls.DropDownList progressBarLocationDropDown;
        protected System.Web.UI.WebControls.DropDownList buttonTypeDropDown;
        protected Hitone.Web.SqlServerUploader.SqlServerInputFile inputFile;
        protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
        protected Hitone.Web.SqlServerUploader.SqlServerInputFile inputFile2;
        protected System.Web.UI.HtmlControls.HtmlGenericControl submitButtonSpan;
        protected System.Web.UI.WebControls.Button submitButton;
        protected System.Web.UI.WebControls.Button cancelButton;
        protected System.Web.UI.HtmlControls.HtmlGenericControl commandButtonSpan;
        protected System.Web.UI.WebControls.Button commandButton;
        protected System.Web.UI.WebControls.Button cancelCommandButton;
        protected System.Web.UI.HtmlControls.HtmlGenericControl linkButtonSpan;
        protected System.Web.UI.WebControls.LinkButton linkButton;
        protected System.Web.UI.WebControls.LinkButton cancelLinkButton;
        protected System.Web.UI.HtmlControls.HtmlGenericControl bodyPre;
        protected System.Web.UI.HtmlControls.HtmlGenericControl inlineProgressBarDiv;
        protected Brettle.Web.NeatUpload.ProgressBar inlineProgressBar;
        protected System.Web.UI.HtmlControls.HtmlGenericControl popupProgressBarDiv;
        protected Brettle.Web.NeatUpload.ProgressBar progressBar;
        protected System.Web.UI.WebControls.Label label;
    }
}
